/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BarterRequestDTO
 */
export interface BarterRequestDTO {
    /**
     * 
     * @type {number}
     * @memberof BarterRequestDTO
     */
    receiverUserId?: number;
    /**
     * 
     * @type {string}
     * @memberof BarterRequestDTO
     */
    taskDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof BarterRequestDTO
     */
    offeredSkill?: string;
    /**
     * 
     * @type {string}
     * @memberof BarterRequestDTO
     */
    requestedSkill?: string;
    /**
     * 
     * @type {number}
     * @memberof BarterRequestDTO
     */
    senderEstimatedHours?: number;
    /**
     * 
     * @type {number}
     * @memberof BarterRequestDTO
     */
    receiverEstimatedHours?: number;
}

/**
 * Check if a given object implements the BarterRequestDTO interface.
 */
export function instanceOfBarterRequestDTO(value: object): value is BarterRequestDTO {
    return true;
}

export function BarterRequestDTOFromJSON(json: any): BarterRequestDTO {
    return BarterRequestDTOFromJSONTyped(json, false);
}

export function BarterRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BarterRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'receiverUserId': json['receiverUserId'] == null ? undefined : json['receiverUserId'],
        'taskDescription': json['taskDescription'] == null ? undefined : json['taskDescription'],
        'offeredSkill': json['offeredSkill'] == null ? undefined : json['offeredSkill'],
        'requestedSkill': json['requestedSkill'] == null ? undefined : json['requestedSkill'],
        'senderEstimatedHours': json['senderEstimatedHours'] == null ? undefined : json['senderEstimatedHours'],
        'receiverEstimatedHours': json['receiverEstimatedHours'] == null ? undefined : json['receiverEstimatedHours'],
    };
}

export function BarterRequestDTOToJSON(json: any): BarterRequestDTO {
    return BarterRequestDTOToJSONTyped(json, false);
}

export function BarterRequestDTOToJSONTyped(value?: BarterRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'receiverUserId': value['receiverUserId'],
        'taskDescription': value['taskDescription'],
        'offeredSkill': value['offeredSkill'],
        'requestedSkill': value['requestedSkill'],
        'senderEstimatedHours': value['senderEstimatedHours'],
        'receiverEstimatedHours': value['receiverEstimatedHours'],
    };
}

