/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillDTO
 */
export interface SkillDTO {
    /**
     * 
     * @type {string}
     * @memberof SkillDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillDTO
     */
    proficiency?: string;
}

/**
 * Check if a given object implements the SkillDTO interface.
 */
export function instanceOfSkillDTO(value: object): value is SkillDTO {
    return true;
}

export function SkillDTOFromJSON(json: any): SkillDTO {
    return SkillDTOFromJSONTyped(json, false);
}

export function SkillDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'proficiency': json['proficiency'] == null ? undefined : json['proficiency'],
    };
}

export function SkillDTOToJSON(json: any): SkillDTO {
    return SkillDTOToJSONTyped(json, false);
}

export function SkillDTOToJSONTyped(value?: SkillDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'proficiency': value['proficiency'],
    };
}

